### ISSUE TITLE
Library version 1.0.2 prints the words in console

### ISSUE THREAD

**Issue by fodil-a** [justkawal/animated_text#3]
When using version `1.0.2` of `animated_text` I see logs containing the animated words in console.
After debugging, I found the culprit, something looking like `print(words.toString());`.

Since this code is present in the version 1.0.2 and not on git, my guess it that you did the release with a non-clean git tree,  you just have to do a new clean release (1.0.3 ?) to fix this issue.

**Comment by justkawal** [comment]
@fodil-a 
In the upcoming version with null-safety support, I'll take care that it will not print such stuff.
